namespace RobinHood70.Robby
{
	using System;

	/// <summary>Represents a warning generated by Robby or, by extension, the wiki itself.</summary>
	/// <seealso cref="EventArgs" />
	public class WarningEventArgs : EventArgs
	{
		#region Constructors

		/// <summary>Initializes a new instance of the <see cref="WarningEventArgs"/> class.</summary>
		/// <param name="sender">The sender of the warning.</param>
		/// <param name="warning">The warning text.</param>
		public WarningEventArgs(IMessageSource sender, string warning)
		{
			this.Sender = sender;
			this.Warning = warning;
		}
		#endregion

		#region Public Properties

		/// <summary>Gets the sender of the warning.</summary>
		/// <value>The sender of the warning.</value>
		public IMessageSource Sender { get; }

		/// <summary>Gets the warning text.</summary>
		/// <value>The warning text.</value>
		public string Warning { get; }
		#endregion
	}
}
