namespace RobinHood70.Robby.Design
{
	/// <summary>Interface for Title-like objects.</summary>
	public interface IWikiTitle
	{
		#region Properties

		/// <summary>Gets the full name of the page.</summary>
		/// <value>The full name of the page.</value>
		string FullPageName { get; }

		/// <summary>Gets the key.</summary>
		/// <value>The key.</value>
		/// <autogeneratedoc />
		string Key { get; }

		/// <summary>Gets the namespace.</summary>
		/// <value>The namespace.</value>
		/// <autogeneratedoc />
		Namespace Namespace { get; }

		/// <summary>Gets the name of the page without the namespace.</summary>
		/// <value>The name of the page without the namespace.</value>
		string PageName { get; }

		/// <summary>Gets the site.</summary>
		/// <value>The site.</value>
		/// <autogeneratedoc />
		Site Site { get; }
		#endregion

		// CONSIDER: Should these be required methods.
		#region Methods

		// bool IsIdenticalTo(IWikiTitle title);

		// bool IsSameAs(IWikiTitle title);
		#endregion
	}
}