namespace RobinHood70.WallE.Clients
{
	using System;
	using RobinHood70.WikiCommon;

	/// <summary>The reason for requested delay.</summary>
	public enum DelayReason
	{
		/// <summary>A client requested a throttle not generated by the site.</summary>
		ClientThrottled,

		/// <summary>The site returned an error and we're delaying until it's time to retry.</summary>
		Error,

		/// <summary>The site is throttling logins due to multiple retries.</summary>
		LoginThrottled,

		/// <summary>The site returned a maxlag result.</summary>
		MaxLag
	}

	/// <summary>Specifies the events and methods required by all client implementations.</summary>
	public interface IMediaWikiClient
	{
		#region Events

		/// <summary>The event raised when either the site or the client is requesting a delay.</summary>
		event StrongEventHandler<IMediaWikiClient, DelayEventArgs> RequestingDelay;
		#endregion

		#region Methods

		/// <summary>Deletes all cookies from persistent storage and clears the cookie cache.</summary>
		void DeleteCookies();

		/// <summary>Downloads a file directly to disk instead of returning it as a string.</summary>
		/// <param name="uri">The URI to download from.</param>
		/// <param name="fileName">The filename to save to.</param>
		/// <returns><see langword="true"/> if the download succeeded; otherwise <see langword="false"/>.</returns>
		bool DownloadFile(Uri uri, string fileName);

		/// <summary>Gets the text of the result returned by the given URI.</summary>
		/// <param name="uri">The URI to get.</param>
		/// <returns>The text of the result.</returns>
		string Get(Uri uri);

		/// <summary>Retrieves cookies from persistent storage.</summary>
		void LoadCookies();

		/// <summary>POSTs text data and retrieves the result.</summary>
		/// <param name="uri">The URI to POST data to.</param>
		/// <param name="postData">The text to POST.</param>
		/// <returns>The text of the result.</returns>
		string Post(Uri uri, string postData);

		/// <summary>POSTs byte data and retrieves the result.</summary>
		/// <param name="uri">The URI to POST data to.</param>
		/// <param name="contentType">The text of the content type. Typicially "<c>x-www-form-urlencoded</c>" or "<c>multipart/form-data ...</c>", but there is no restriction on values.</param>
		/// <param name="postData">The byte array to POST.</param>
		/// <returns>The text of the result.</returns>
		string Post(Uri uri, string contentType, byte[] postData);

		/// <summary>This method is used both to throttle clients as well as to forward any wiki-requested delays, such as from maxlag. Clients should respect any delays requested by the wiki unless they expect to abort the procedure, or for testing.</summary>
		/// <param name="delayTime">The amount of time to delay for.</param>
		/// <param name="reason">The reason for the delay, as specified by the caller.</param>
		/// <param name="description">The human-readable reason for the delay, as specified by the caller.</param>
		/// <returns>A value indicating whether or not the delay was respected.</returns>
		bool RequestDelay(TimeSpan delayTime, DelayReason reason, string description);

		/// <summary>Saves all cookies to persistent storage.</summary>
		void SaveCookies();
		#endregion
	}
}
