//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobinHood70.HoodBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobinHood70.HoodBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL to any page on the wiki:.
        /// </summary>
        public static string AnyWikiPage {
            get {
                return ResourceManager.GetString("AnyWikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Path:.
        /// </summary>
        public static string ApiPath {
            get {
                return ResourceManager.GetString("ApiPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Jobs:.
        /// </summary>
        public static string AvailableJobs {
            get {
                return ResourceManager.GetString("AvailableJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Wiki List.
        /// </summary>
        public static string EditWikiList {
            get {
                return ResourceManager.GetString("EditWikiList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Completion:.
        /// </summary>
        public static string EstimatedCompletion {
            get {
                return ResourceManager.GetString("EstimatedCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC:.
        /// </summary>
        public static string EstimatedCompletionUTC {
            get {
                return ResourceManager.GetString("EstimatedCompletionUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in automatically.
        /// </summary>
        public static string FillInAutomatically {
            get {
                return ResourceManager.GetString("FillInAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoodBot.
        /// </summary>
        public static string HoodBotMainWindow {
            get {
                return ResourceManager.GetString("HoodBotMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the Wiki Name and the API Path must be filled in..
        /// </summary>
        public static string InvalidWikiInfo {
            get {
                return ResourceManager.GetString("InvalidWikiInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application could not start because ApplicationData path could not be created. See InnerException for details..
        /// </summary>
        public static string NoAppDataPath {
            get {
                return ResourceManager.GetString("NoAppDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Throttle:.
        /// </summary>
        public static string ReadThrottle {
            get {
                return ResourceManager.GetString("ReadThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Parameters.
        /// </summary>
        public static string RequiredInfo {
            get {
                return ResourceManager.GetString("RequiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki:.
        /// </summary>
        public static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Name:.
        /// </summary>
        public static string WikiName {
            get {
                return ResourceManager.GetString("WikiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Throttle:.
        /// </summary>
        public static string WriteThrottle {
            get {
                return ResourceManager.GetString("WriteThrottle", resourceCulture);
            }
        }
    }
}
