//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobinHood70.Robby.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobinHood70.Robby.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local dictionary and items list are out of sync..
        /// </summary>
        internal static string DictionaryListOutOfSync {
            get {
                return ResourceManager.GetString("DictionaryListOutOfSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has no revisions or the Uri for the file is null..
        /// </summary>
        internal static string FileRevisionInvalid {
            get {
                return ResourceManager.GetString("FileRevisionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of LimitationType is invalid..
        /// </summary>
        internal static string InvalidLimitationType {
            get {
                return ResourceManager.GetString("InvalidLimitationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempted to use an object from one site with an object from another..
        /// </summary>
        internal static string InvalidSite {
            get {
                return ResourceManager.GetString("InvalidSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt to log in to the wiki failed: {0}.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The internal site information object is missing required values..
        /// </summary>
        internal static string MissingSiteInfo {
            get {
                return ResourceManager.GetString("MissingSiteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving page [[{0}]] to [[{1}]] failed: {{2}}.
        /// </summary>
        internal static string MovePageWarning {
            get {
                return ResourceManager.GetString("MovePageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace provided is not valid. It must be {0}..
        /// </summary>
        internal static string NamespaceMustBe {
            get {
                return ResourceManager.GetString("NamespaceMustBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page {0} could not be loaded, probably because it&apos;s not an article or the title is invalid..
        /// </summary>
        internal static string PageCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("PageCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid until the site has been initialized..
        /// </summary>
        internal static string SiteNotInitialized {
            get {
                return ResourceManager.GetString("SiteNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size value invalid..
        /// </summary>
        internal static string SizeInvalid {
            get {
                return ResourceManager.GetString("SizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title name cannot be blank..
        /// </summary>
        internal static string TitleInvalid {
            get {
                return ResourceManager.GetString("TitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to send an e-mail to this user..
        /// </summary>
        internal static string UserEmailDisabled {
            get {
                return ResourceManager.GetString("UserEmailDisabled", resourceCulture);
            }
        }
    }
}
