//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobinHood70.WikiClasses.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobinHood70.WikiClasses.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymizing parameter {0} put it into position {1} instead of {2}..
        /// </summary>
        internal static string AnonymizeBad {
            get {
                return ResourceManager.GetString("AnonymizeBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should never be called on the Root Stack Element..
        /// </summary>
        internal static string CalledOnRoot {
            get {
                return ResourceManager.GetString("CalledOnRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text provided to {0}.{1} was malformed..
        /// </summary>
        internal static string MalformedNodeText {
            get {
                return ResourceManager.GetString("MalformedNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} called multiple times. It should only ever be called once on a given object..
        /// </summary>
        internal static string MultipleCalls {
            get {
                return ResourceManager.GetString("MultipleCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter \&quot;{0}\&quot; already exists..
        /// </summary>
        internal static string ParameterExists {
            get {
                return ResourceManager.GetString("ParameterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack is empty or you attempted to pop the root node..
        /// </summary>
        internal static string PoppedRoot {
            get {
                return ResourceManager.GetString("PoppedRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different numbers of &apos;=&apos; in Section title..
        /// </summary>
        internal static string SectionLevelMismatch {
            get {
                return ResourceManager.GetString("SectionLevelMismatch", resourceCulture);
            }
        }
    }
}
